#!/bin/bash

# run matplotlib once to generate the font cache
python -c "from webdriverdownloader import GeckoDriverDownloader; 
gdd = GeckoDriverDownloader(); 
gdd.download_and_install("v0.23.0")
"
